bucket_origin_id = "post-reader-website-origin-id"
bucket_tag_name  = "Post Reader Hosting"
waf_ipset_name   = "postReaderIPSet"
waf_rule_name    = "postReaderWAFRule"
waf_web_acl_name = "postReaderWebACL"
