import { booleanAttribute, ChangeDetectionStrategy, Component, HostBinding, Input } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-ai',
  template: `<div><ng-content></ng-content></div>
    <mark>{{ content }} <lucide-icon name="wand" [size]="15" [strokeWidth]="2"></lucide-icon></mark>`,
  styles: [
    `
      :host {
        display: inline-flex;
        flex-direction: column;
        margin: 15px 0 10px;
        font-size: 0.75rem;
        border: 1px solid var(--green);
        color: var(--green);
        border-radius: 8px;
        padding: 2px 8px;
        &.failed {
          border: 1px solid var(--red);
          color: var(--red);
          mark {
            color: var(--red);
          }
        }
      }

      div {
        font-style: italic;
        &:not(:empty) {
          &::before {
            content: '\u201C';
          }
          &::after {
            content: '\u201D';
          }
          + mark {
            margin-top: 5px;
          }
        }
      }

      mark {
        display: inline-flex;
        gap: 5px;
        align-items: center;
        background: transparent;
        color: var(--green);
      }
    `
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule],
  standalone: true
})
export class AiComponent {
  @HostBinding('class.failed')
  @Input({ transform: booleanAttribute })
  failed = false;

  get content(): string {
    return this.failed ? 'No article summary generated' : 'Article summary generated by AI';
  }
}
